[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11.0

[font.bold]
family = "DejaVuSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font"
style = "Bold Oblique"

[font.italic]
family = "DejaVuSansM Nerd Font"
style = "Oblique"

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[terminal]
shell = "/opt/homebrew/bin/fish"

[window]
decorations = "none"
opacity = 0.85
startup_mode = "Maximized"
option_as_alt = "Both"

[cursor]
style = { shape = "Block", blinking = "Always" }
